---
- name: reload elasticsearch
  service: name=elasticsearch state=reloaded
  become: true
  become_user: root

- name: restart elasticsearch
  service: name=elasticsearch state=restarted
  become: true
  become_user: root
