---
- name: .NET | Make sure HTTPS is supported by apt
  package:
    name: apt-transport-https
    state: present
    update_cache: true

- name: .NET | Add apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  register: result
  until: '"failed" not in result'
  retries: 3
  delay: 5

- name: .NET | Add repo for Ubuntu Trusty
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

- name: .NET | Add repo for Ubuntu Xenial
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

- name: .NET | Install dotnet core SDK
  package:
    name: "{{ dotnet_ubuntu_package }}"
    state: present
    update_cache: true
  register: result
  until: '"failed" not in result'
  retries: 3
  delay: 5