apt_cache_valid_time: 600
apt_java_repo: ppa:webupd8team/java
apt_java_package: oracle-java8-installer

java_security_policies: []

codename_apt_codename_map:
  - release_codename: jessie
    use_apt_codename: xenial
  - release_codename: stretch
    use_apt_codename: xenial