---
- name: reload postgresql
  service: name=postgresql state=reloaded
  become: true
  become_user: root

- name: restart postgresql
  service: name=postgresql state=restarted
  become: true
  become_user: root
