---
- name: Assert platform is supported
  tags: geoserver
  assert:
    that:
      - ansible_os_family in ['Ubuntu', 'Debian']

- name: Download Geoserver (remote)
  tags: geoserver
  get_url:
    dest: "/tmp/geoserver.war"
    url: "{{ geoserver_download_url }}"
    force: yes
    owner: 0
    group: 0
    mode: 0644

- name: install unzip
  apt: pkg={{ item }} state=installed force=yes
  with_items:
    - unzip

- name: Unpack & deploy geoserver.war
  unarchive:
    src: "/tmp/geoserver.war"
    dest: "/var/lib/tomcat{{ tomcat_version }}/webapps"
    remote_src: yes

